 
version: '3'
services:
  web:
    image: alanlab/cluster_app:banco_v5
    ports:
      - "80:3000"
    environment:
      DATABASE_HOST: database 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
    depends_on:
      - database
  db-migration:
    image: alanlab/cluster_app:banco_v5
    command: ["./wait-for", "--timeout=300", "database:5432", "--", "bin/rails", "db:migrate", "RAILS_ENV=production"]
    environment:
      DATABASE_HOST: database 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
    links:
      - database
    depends_on:
      - database  
    deploy:
      restart_policy:
        condition: none
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: